/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Headers: typeof import('./src/components/Headers.vue')['default']
    IndexContainer: typeof import('./src/components/IndexContainer.vue')['default']
    Loading: typeof import('./src/components/component/loading.vue')['default']
    RgbInput: typeof import('./src/components/RgbInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Running: typeof import('./src/components/Running.vue')['default']
    RunningCard: typeof import('./src/components/RunningCard.vue')['default']
    Runnning: typeof import('./src/components/Runnning.vue')['default']
    Search: typeof import('./src/components/component/Search.vue')['default']
    SecondHeaders: typeof import('./src/components/SecondHeaders.vue')['default']
  }
}
